name: CI when a PR to main opened, synchronized, or reopened

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  checkout-and-build:
    # Môi trường chạy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    # Các bước thực hiện
    steps:
      - name: Checkout code from source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Log information
        run: |
          echo "Pull Request #${{ github.event.number }} opened by ${{ github.event.pull_request.user.login }}"
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build and Test
        run: |
          npm ci
          npm run build
          # npm test
