name: CI when a PR to main opened

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build-and-push:
    # Môi trường chạy
    runs-on: ubuntu-latest

    # Các bước thực hiện
    steps:
      - name: Checkout code from source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
